[
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "marriott.com",
  },
  {
    country:
      "美国,加拿大,英国,澳大利亚,新西兰,墨西哥,日本,韩国,德国,法国,意大利,荷兰,西班牙,葡萄牙,波兰,瑞典,奥地利,捷克,丹麦,芬兰,希腊,匈牙利,爱尔兰,其他",
    enCountry:
      "美国,加拿大,英国,澳大利亚,新西兰,墨西哥,日本,韩国,德国,法国,意大利,荷兰,西班牙,葡萄牙,波兰,瑞典,奥地利,捷克,丹麦,芬兰,希腊,匈牙利,爱尔兰,其他",
    status: "processed",
    url: "temu.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "evereve.com" },
  {
    country: "澳大利亚,美国,德国,英国",
    enCountry: "澳大利亚,美国,德国,英国",
    status: "processed",
    url: "farfetch.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "spanx.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "aloyoga.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "moss.co.uk",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "newbalance.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "max.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "boden.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "loft.com" },
  {
    country: "香港",
    enCountry: "香港",
    status: "processed",
    url: "adidas.com.hk",
  },
  {
    country: "美国,加拿大,德国,法国,英国",
    enCountry: "美国,加拿大,德国,法国,英国",
    status: "processed",
    url: "whatnot.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "samsung.com" },
  {
    country: "英国,其他",
    enCountry: "英国,其他",
    status: "processed",
    url: "lookfantastic.com",
  },
  {
    country: "澳大利亚,美国,加拿大,英国,其他",
    enCountry: "澳大利亚,美国,加拿大,英国,其他",
    status: "processed",
    url: "cettire.com",
  },
  {
    country: "巴西,澳大利亚,加拿大,新西兰,其他",
    enCountry: "巴西,澳大利亚,加拿大,新西兰,其他",
    status: "processed",
    url: "primevideo.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "revolve.com",
  },
  {
    country: "美国,加拿大,澳大利亚",
    enCountry: "美国,加拿大,澳大利亚",
    status: "processed",
    url: "fragrancenet.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "debenhams.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "ramybrook.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "newlook.com" },
  {
    country: "澳大利亚,美国,加拿大,英国,其他",
    enCountry: "澳大利亚,美国,加拿大,英国,其他",
    status: "processed",
    url: "expedia.com",
  },
  {
    country: "日本,澳大利亚,美国,加拿大,德国,英国,其他",
    enCountry: "日本,澳大利亚,美国,加拿大,德国,英国,其他",
    status: "processed",
    url: "theoutnet.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "thegldshop.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "shopbop.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "ssense.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "marksandspencer.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "princesspolly.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "basspro.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "etsy.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "ruelala.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "urbanoutfitters.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "fleetfeet.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "maurices.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "misfitsmarket.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "boots.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "schoolhouse.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "budget.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "stockx.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "gamestop.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "diy.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "saksfifthavenue.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "saksoff5th.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "hsn.com" },
  {
    country:
      "奥地利,比利时,丹麦,捷克,芬兰,希腊,匈牙利,欧盟,意大利,立陶宛,卢森堡,波兰,罗马尼亚,葡萄牙,爱尔兰,瑞典,西班牙,英国",
    enCountry:
      "奥地利,比利时,丹麦,捷克,芬兰,希腊,匈牙利,欧盟,意大利,立陶宛,卢森堡,波兰,罗马尼亚,葡萄牙,爱尔兰,瑞典,西班牙,英国",
    status: "processed",
    url: "drmartens.com",
  },
  {
    country: "澳大利亚,美国,加拿大,英国,其他",
    enCountry: "澳大利亚,美国,加拿大,英国,其他",
    status: "processed",
    url: "saatva.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "lulus.com" },
  {
    country: "加拿大,英国,美国",
    enCountry: "加拿大,英国,美国",
    status: "processed",
    url: "shaneco.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "1800contacts.com",
  },
  { country: "其他", enCountry: "其他", status: "processed", url: "lego.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "hoka.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "tommy.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "viagogo.com",
  },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "neimanmarcus.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "shoepalace.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "lskd.co" },
  { country: "美国", enCountry: "us", status: "processed", url: "ulta.com" },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "myprotein.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "squarespace.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "armani.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "selfridges.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "crocs.com" },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "superdrug.com",
  },
  {
    country: "挪威",
    enCountry: "no",
    status: "processed",
    url: "scandichotels.no",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "coldwatercreek.com",
  },
  {
    country: "澳大利亚,芬兰,波兰,奥地利,法国,西班牙,比利时,德国,瑞典,丹麦,其他",
    enCountry:
      "澳大利亚,芬兰,波兰,奥地利,法国,西班牙,比利时,德国,瑞典,丹麦,其他",
    status: "processed",
    url: "ecco.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "academy.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "weekday.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "fahertybrand.com",
  },
  { country: "法国", enCountry: "fr", status: "processed", url: "manomano.fr" },
  {
    country: "英国,欧盟,中国,美国",
    enCountry: "英国,欧盟,中国,美国",
    status: "processed",
    url: "cultbeauty.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "revzilla.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "ariat.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "gymshark.com",
  },
  {
    country: "欧洲（非欧盟）",
    enCountry: "欧洲（非欧盟）",
    status: "processed",
    url: "stories.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "tecovas.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "adidas.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "dolcevita.com",
  },
  {
    country: "加拿大,澳大利亚,英国,新西兰,美国,其他",
    enCountry: "加拿大,澳大利亚,英国,新西兰,美国,其他",
    status: "processed",
    url: "coursehero.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "etihad.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "staud.clothing",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "uniqlo.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "thereformation.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "remarkable.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "bloomingdales.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "mnml.la" },
  {
    country: "加拿大,澳大利亚,美国",
    enCountry: "加拿大,澳大利亚,美国",
    status: "processed",
    url: "bonobos.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "softsurroundings.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "lycamobile.us",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "zazzle.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "trysnow.com",
  },
  {
    country: "加拿大",
    enCountry: "ca",
    status: "processed",
    url: "viator.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "immersivegamebox.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "macduggal.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "loveshackfancy.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "latamairlines.com",
  },
  { country: "欧盟", enCountry: "欧盟", status: "processed", url: "cos.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "shapermint.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "oliveyoung.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "finishline.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "kickscrew.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "net-a-porter.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "beginningboutique.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "parachutehome.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "asos.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "teepublic.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "windsorstore.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "lavishalice.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "clubllondon.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "dickies.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "24s.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "bedbathandbeyond.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "radleylondon.com",
  },
  {
    country:
      "中国,亚太地区,日本,澳大利亚,新加坡,马来西亚,香港,巴西,新西兰,印尼,印度,泰国,美国,英国",
    enCountry:
      "中国,亚太地区,日本,澳大利亚,新加坡,马来西亚,香港,巴西,新西兰,印尼,印度,泰国,美国,英国",
    status: "processed",
    url: "harveynichols.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "scheels.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "versace.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "seraphine.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "brooksrunning.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "iliabeauty.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "abask.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "boggbag.com" },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "ankersolix.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "bergdorfgoodman.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "lagence.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "mrporter.com",
  },
  {
    country: "法国",
    enCountry: "fr",
    status: "processed",
    url: "nvgallery.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "dickssportinggoods.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "vivaia.com",
  },
  { country: "法国", enCountry: "fr", status: "processed", url: "zooplus.fr" },
  {
    country: "澳大利亚",
    enCountry: "au",
    status: "processed",
    url: "ryderwear.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "toryburch.com",
  },
  { country: "加拿大", enCountry: "ca", status: "processed", url: "adidas.ca" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "airalo.com",
  },
  { country: "英国", enCountry: "uk", status: "processed", url: "uklash.com" },
  { country: "全球", enCountry: "全球", status: "processed", url: "klook.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "frankandeileen.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "ugg.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "redwingshoes.com",
  },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "venusetfleur.com",
  },
  {
    country: "比利时,法国",
    enCountry: "比利时,法国",
    status: "processed",
    url: "citadium.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "sermo.com" },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "journeys.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "bugaboo.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "avis.com" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "newegg.com",
  },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "homage.com",
  },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "davidsbridal.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "mytheresa.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "intimissimi.com",
  },
  {
    country: "美国,全球",
    enCountry: "美国,全球",
    status: "processed",
    url: "becker.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "isabelmarant.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "samsclub.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "consumercellular.com",
  },
  {
    country: "加拿大,英国,美国",
    enCountry: "加拿大,英国,美国",
    status: "processed",
    url: "fromourplace.com",
  },
  {
    country: "美国,加拿大",
    enCountry: "美国,加拿大",
    status: "processed",
    url: "stubhub.com",
  },
  {
    country: "澳大利亚,其他",
    enCountry: "澳大利亚,其他",
    status: "processed",
    url: "boody.com.au",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "bbqguys.com" },
  {
    country: "美国,加拿大",
    enCountry: "美国,加拿大",
    status: "processed",
    url: "23andme.com",
  },
  {
    country: "加拿大,法国,澳大利亚,西班牙,意大利,德国,美国,荷兰,其他",
    enCountry: "加拿大,法国,澳大利亚,西班牙,意大利,德国,美国,荷兰,其他",
    status: "processed",
    url: "grownbrilliance.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "dtlr.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "publicstorage.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "heydudeshoesusa.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "karenkane.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "tomboyx.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "laurageller.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "jtv.com" },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "diesel.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "icklebubba.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "tous.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "mgemi.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "totalwine.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "sohohome.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "xtool.com" },
  {
    country: "加拿大,美国",
    enCountry: "加拿大,美国",
    status: "processed",
    url: "flutterhabit.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "skinnydiplondon.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "drberg.com",
  },
  { country: "加拿大", enCountry: "ca", status: "processed", url: "voila.ca" },
  { country: "美国", enCountry: "us", status: "processed", url: "milly.com" },
  {
    country: "澳大利亚,中国,奥地利,德国,巴西,日本,英国,加拿大,瑞典,美国,其他",
    enCountry: "澳大利亚,中国,奥地利,德国,巴西,日本,英国,加拿大,瑞典,美国,其他",
    status: "processed",
    url: "athleticpropulsionlabs.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "yasisland.com",
  },
  {
    country: "比利时,荷兰,德国,西班牙,法国,欧盟,意大利,瑞典,英国,其他",
    enCountry: "比利时,荷兰,德国,西班牙,法国,欧盟,意大利,瑞典,英国,其他",
    status: "processed",
    url: "monki.com",
  },
  {
    country: "加拿大,英国,美国",
    enCountry: "加拿大,英国,美国",
    status: "processed",
    url: "fieracosmetics.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "shopcider.com",
  },
  {
    country: "加拿大,法国,澳大利亚,英国,西班牙,意大利,德国,美国,荷兰,其他",
    enCountry: "加拿大,法国,澳大利亚,英国,西班牙,意大利,德国,美国,荷兰,其他",
    status: "processed",
    url: "bloomchic.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "fender.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "globalgolf.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "iherb.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "masterclass.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "dvf.com" },
  {
    country: "美国,加拿大,法国,英国,瑞典",
    enCountry: "美国,加拿大,法国,英国,瑞典",
    status: "processed",
    url: "hotels.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "lookoptic.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processing",
    url: "saint-james.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "thetiebar.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "baltini.com" },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "hannaandersson.com",
  },
  {
    country: "英国",
    enCountry: "uk",
    status: "processed",
    url: "broraonline.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "mintmobile.com",
  },
  {
    country: "澳大利亚,美国",
    enCountry: "澳大利亚,美国",
    status: "processed",
    url: "petalandpup.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "psychobunny.com",
  },
  {
    country: "美国,加拿大",
    enCountry: "美国,加拿大",
    status: "processed",
    url: "paulayoung.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "food52.com" },
  { country: "美国", enCountry: "us", status: "processed", url: "levi.com" },
  {
    country: "法国",
    enCountry: "fr",
    status: "processed",
    url: "maje.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "superjeweler.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "hudabeauty.com",
  },
  {
    country: "英国,美国",
    enCountry: "英国,美国",
    status: "processed",
    url: "wolfandbadger.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "paulsmith.com",
  },
  {
    country:
      "澳大利亚,法国,瑞典,奥地利,德国,意大利,英国,加拿大,日本,美国,芬兰,西班牙,其他",
    enCountry:
      "澳大利亚,法国,瑞典,奥地利,德国,意大利,英国,加拿大,日本,美国,芬兰,西班牙,其他",
    status: "processed",
    url: "ferragamo.com",
  },
  { country: "全球", enCountry: "全球", status: "processed", url: "roots.com" },
  {
    country: "法国,英国,西班牙,意大利,德国,美国,荷兰",
    enCountry: "法国,英国,西班牙,意大利,德国,美国,荷兰",
    status: "processed",
    url: "casadei.com",
  },
  { country: "美国", enCountry: "us", status: "processed", url: "asics.com" },
  {
    country: "意大利,美国,西班牙,法国,英国",
    enCountry: "意大利,美国,西班牙,法国,英国",
    status: "processed",
    url: "discovercars.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "jamesmichelle.com",
  },
  {
    country: "其他,希腊",
    enCountry: "其他,希腊",
    status: "processed",
    url: "libertylondon.com",
  },
  {
    country: "澳大利亚,加拿大,英国,美国",
    enCountry: "澳大利亚,加拿大,英国,美国",
    status: "processed",
    url: "meritbeauty.com",
  },
  {
    country: "巴西",
    enCountry: "br",
    status: "processed",
    url: "madesa.com",
  },
  {
    country: "加拿大",
    enCountry: "ca",
    status: "processed",
    url: "walmart.ca",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "harperwilde.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "bostonproper.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "littlewordsproject.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "tractive.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "fellahealth.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "saboskirt.com",
  },
  { country: "德国", enCountry: "de", status: "processed", url: "memorypc.de" },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "malbon.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "beulahlondon.com",
  },
  {
    country: "其他,澳大利亚,意大利,波兰,奥地利,葡萄牙,比利时,日本,巴西",
    enCountry: "其他,澳大利亚,意大利,波兰,奥地利,葡萄牙,比利时,日本,巴西",
    status: "processed",
    url: "liforme.com",
  },
  {
    country: "美国",
    enCountry: "us",
    status: "processed",
    url: "fentybeauty.com",
  },
  {
    country: "全球",
    enCountry: "全球",
    status: "processed",
    url: "spinnakerboutique.com",
  },
];
